In [1]:
import pandas as pd

## 1.)

In [2]:
# California Housing Prices Dataset
url = 'https://github.com/ageron/handson-ml/raw/master/datasets/housing/housing.csv'

df = pd.read_csv(url)

# Viewing the dataset
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [3]:
# Viewing the first 5 rows of the dataset
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
# Get dimensions of dataset
df.shape

(20640, 10)

In [5]:
# Confirming the dataset has missing values
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

___

## 2.a)

In [6]:
# Printing columns and rows of the dataset
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])


Number of rows: 20640
Number of columns: 10


___


## 2.b)
In the context of the dataset:
- Variables are the characteristics or attributes of the data being measured; they are parameters where each instance of the data has to be measured on. 
- Observations are the specific individual records of the data.

To further simplify, the columns represent the variables while each row represents the observations.

___

## 3.)
### Generating simple summaries of the columns in a dataset

In [7]:
# Using describe()
print(df.describe())
df.describe()

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.00000

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [8]:
# Using info()
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB
None


In [9]:
# Using value_counts() for a preferably non-numerical column.
print(df['ocean_proximity'].value_counts())

# 9136 + 6551 + 2658 + 2290 + 5 = 20640

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64


In [10]:
# Using mean(), median(), and std() for columns with numeric values

print(df['longitude'].mean())
print(df['longitude'].median())
print(df['longitude'].std())

-119.56970445736432
-118.49
2.003531723502581


In [11]:
# Using groupby()
print(df.groupby('ocean_proximity').mean())

                  longitude   latitude  housing_median_age  total_rooms  \
ocean_proximity                                                           
<1H OCEAN       -118.847766  34.560577           29.279225  2628.343586   
INLAND          -119.732990  36.731829           24.271867  2717.742787   
ISLAND          -118.354000  33.358000           42.400000  1574.600000   
NEAR BAY        -122.260694  37.801057           37.730131  2493.589520   
NEAR OCEAN      -119.332555  34.738439           29.347254  2583.700903   

                 total_bedrooms   population  households  median_income  \
ocean_proximity                                                           
<1H OCEAN            546.539185  1520.290499  517.744965       4.230682   
INLAND               533.881619  1391.046252  477.447565       3.208996   
ISLAND               420.400000   668.000000  276.600000       2.744420   
NEAR BAY             514.182819  1230.317467  488.616157       4.172885   
NEAR OCEAN           538

In [12]:
# Using corr()
# Apparently this method only works on numeric values, so I used the argument 'numeric_only = True' to only use the numeric variables of the dataset.

print(df.corr(numeric_only = True))

                    longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924664           -0.108197     0.044568   
latitude            -0.924664  1.000000            0.011173    -0.036100   
housing_median_age  -0.108197  0.011173            1.000000    -0.361262   
total_rooms          0.044568 -0.036100           -0.361262     1.000000   
total_bedrooms       0.069608 -0.066983           -0.320451     0.930380   
population           0.099773 -0.108785           -0.296244     0.857126   
households           0.055310 -0.071035           -0.302916     0.918484   
median_income       -0.015176 -0.079809           -0.119034     0.198050   
median_house_value  -0.045967 -0.144160            0.105623     0.134153   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069608    0.099773    0.055310      -0.015176   
latitude                 -0.066983   -0.108785   -0.071035      -0.079809   
housing_

___

## 4.a)

In [13]:
# Identifying if the dataset has non-numeric variables:

print(df.dtypes)

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object


## 4.b)

In [14]:
# Identifying if the dataset has missing values:

numeric_missing_values = df.select_dtypes(include=['number']).isnull().sum()
print("Missing values in numerical columns:\n", numeric_missing_values)

Missing values in numerical columns:
 longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
dtype: int64


## 4.c)
To explain the discrepancies:

For **a) Number of Columns Analzyed**, `df.shape` provides the dimensions of the dataframe while `df.describe()` provides summary statistics only for numerical columns by default. So the discrepancy with respect to **a)** would be that `df.describe` would only summarize the numerical columns and return that as the output.

For **b) Values in the Count Column**, `df.shape` will indicate the total number of rows in the dataset while `df.describe()` will show the non-null values for each numerical column. The discrepancy with respect to **b)** would be that `df.describe` will return the *count* of a column less than the total number of rows if that numerical column has missing values.

**To summarize:**
- `df.shape` will show the exact dimensions of the dataset, while `df.describe()` will only summarize the numerical columns.
- `df.describe()` will return the number of non-null entries in a numerical column, which can be less than the total number of rows if there are missing values.


In [15]:
# Showing the discrepancies:
print("Using df.shape:")
print(df.shape)

print("\nUsing df.describe():")
print(df.describe())

# Notice how the 'ocean_proximity' column is omitted, and the 'total_bedrooms' column has a 'count' that is less than the total number of rows.

Using df.shape:
(20640, 10)

Using df.describe():
          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000   

___

## 5.)
The difference between attributes and methods are based on how they interact with the dataset:

- *Attributes* are used to access information about an object that holds a value.
- *Methods* are *functions* (programming terminology) that perform an action on the object; they can modify the object or return a result based on the object's data.

> Functions in programming terminology refer to a block of code that is designed to execute a specific task

> Functions in Mathematics refer to the relation between a set of inputs and a set of outputs.

We can observe that attributes only return information that an object already has, while methods can return new information based on the object's data or even modify the object itself. This is demonstrated by using `df.describe()` (method) and `df.shape` (attribute). 

___

## 6.)
In `df.describe()`, we can observe that only numerical columns are summarized. That is because `describe()` is designed to provide statistical insights that are better suited for numerical data. We can use `df.describe(include='all')`, but it would return NaN (or "Not a Number") for most of the statistics in the non-numerical column.

Here is what each statistic featured in `df.describe()` means:

> count - represents the number of values present in each column, excluding null or missing values.

> mean - the calculation of the sum of all non-null values divided by the count of non-null values; represents the average value in the column and provides a measure of central tendency.

> std/standard deviation - the standard deviation is the measure of the spread of the values in the column; assessing how much the values deviate from the mean on average. High standard deviations indicate a wide spread of values, while low standard deviations indicate that the values are close to the mean.

> min - represents the smallest number or the minimum value among all non-null values in the column.

> 25% - represents the measure of the lower end of the data distribution; particularly the value below which 25% of the data falls. This term can also be known as the first quartile (Q1).

> 50% - represents the middle value of the column wherein half the values are below this value, and half are above the value. It is a measure of central tendency that is less affected by extremely high or low values (or the 'outliers') than the mean.

> 75% - represents the measure of the higher end of the data distribution; particularly the value below which 75% of the data falls. This term can also be known as the third quartile (Q3).

> max - the largest value or maximum value among all the non-null values in the column.

It can be observed that `df.describe()` ignores missing values when computing summary statistics. In the statistic *count*, for example, *count* only retrieves the number of 'present' values -- which means missing values are disregarded.

___

## 7.)
Comparing `df.dropna()` and `del df['col']`:

In [16]:
# Demonstrating dropna()

df_nonan = df.dropna()
df_nonan 

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [17]:
# Demonstrating del df['col']

df_delcol = df.copy()
del df_delcol['latitude']
df_delcol

longitude  housing_median_age  total_rooms  total_bedrooms  population  \
0        -122.23                41.0        880.0           129.0       322.0   
1        -122.22                21.0       7099.0          1106.0      2401.0   
2        -122.24                52.0       1467.0           190.0       496.0   
3        -122.25                52.0       1274.0           235.0       558.0   
4        -122.25                52.0       1627.0           280.0       565.0   
...          ...                 ...          ...             ...         ...   
20635    -121.09                25.0       1665.0           374.0       845.0   
20636    -121.21                18.0        697.0           150.0       356.0   
20637    -121.22                17.0       2254.0           485.0      1007.0   
20638    -121.32                18.0       1860.0           409.0       741.0   
20639    -121.24                16.0       2785.0           616.0      1387.0   

       households  median_income  median_house_value ocean_proximity  
0           126.0         8.3252            452600.0        NEAR BAY  
1          1138.0         8.3014            358500.0        NEAR BAY  
2           177.0         7.2574            352100.0        NEAR BAY  
3           219.0         5.6431            341300.0        NEAR BAY  
4           259.0         3.8462            342200.0        NEAR BAY  
...           ...            ...                 ...             ...  
20635       330.0         1.5603             78100.0          INLAND  
20636       114.0         2.5568             77100.0          INLAND  
20637       433.0         1.7000             92300.0          INLAND  
20638       349.0         1.8672             84700.0          INLAND  
20639       530.0         2.3886             89400.0          INLAND  

[20640 rows x 9 columns]

___

## 7.a)

We can observe that `dropna()` is preferably used when we intend to 'drop' or remove columns or rows with missing values. The `del df['col']` removes an entire column (which I assume it doesn't work on rows), regardless if it has missing values or not.

> Accuracy and validity are important aspects in Statistics. Accuracy describes the reliability of the data so that they can be used as a trustworthy source of data and/or support better decision-making, while validity ensures that the data is consistent and 'reasonable', based on defined set of rules.

Missing values can affect accuracy and validity in a dataset. So, in the case of a dataset with missing values, `dropna()` is preferred when we want to 'clean' or eliminate null entries from the dataset.

When speaking about the most efficient way to remove missing values, `dropna()` is more efficient than `del` since in `del` we might have to figure out which columns have missing values.

Another thing to take note of is that we can control which axis (rows or columns) to remove when using `dropna()`. Columns are in `axis=1` while rows are represented by `axis=0`. So, `dropna()` will be preferable over `del df['col']` in the case of wanting to remove a row with missing values -- considering that `del df['col']` only works on columns. 

___

## 7.b)
On the other hand, the `del` function is preferably used when we intend to remove a column entirely, regardless if it has missing values.

If we assert that a column is irrelevant to our analysis, we can just use `del df['col']` to remove that column. 

In the case of an irrelevant column in the dataset, `del` is more efficient because we are disregarding if there could be any missing values and more concerned about how relevant a column is.

___

## 7.c)

If we suspect that a column is irrelevant to our analysis and also has missing values, we must first use `del df['col']` before `dropna()`.

This is because if we use `dropna()` first, it would remove rows (assuming we want to remove rows and only rows using `dropna()`) that have missing values in the irrelevant column but non-null values in the relevant columns.

Executing `del df['col']` first ensures that only the relevant data that are necessary for the analysis are present, and no other instances of the data are removed when using `dropna()` -- thus preventing the removal of rows whose entries are valid in the relevant columns, but has a missing value in the irrelevant column.

___

## 7.d)

In [18]:
# In the dataset I provided, we should first see which columns have missing values before taking an approach:
# This is to analyze which columns have missing values and are relevant to the analysis.

df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

It can be observed that the column 'total_bedrooms' have 207 missing values. It would be simplest approach to just remove the column entirely with `del` and not worry anymore about missing values, however the dataset is about the 'California Housing Prices'.

I assume that the total number of bedrooms in a house is relevant in predicting the worth of a house. While there are the columns 'total_rooms' and 'households' which may be used with 'total_bedrooms' to provide, perhaps, more meaningful metrics, we can take a straightforward approach and leave the columns as they are.

They are not 'not relevant'. They might just be less useful depending on the type of analysis one intends to do. 'Less useful', but still useful.

Because I assume that the column 'total_bedrooms' is relevant in the dataset, it is not appropriate to use `del`. The missing values under total_bedrooms also equate to an estimate of 1% of the entire dataset, which I assume is relatively small. Therefore, the approach I would take is to use only `dropna()` on the dataset to remove rows with missing values.

When concerned about efficiency, `dropna()` is still more suitable as we want to remove missing values, and we also want to preserve the column's relevance.



In [19]:
# Before
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [20]:
# After
df_cleaned = df.dropna()
df_cleaned

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [21]:
# We just removed the rows with missing values so 20640 rows - 207 rows equal to 20433 rows.
# No columns are removed.

# To provide more documentation

# Before | Report

shape_before = df.shape
nonan_before = df.isna().sum()
desc_before = df.describe()

print(f"Initial dataset shape: {shape_before}")
print("\nMissing values before using dropna():")
print(nonan_before)
print("\nDataset description before using dropna():")
print(desc_before)

Initial dataset shape: (20640, 10)

Missing values before using dropna():
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Dataset description before using dropna():
          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000        

In [22]:
# After | Report

shape_after = df_cleaned.shape
nonan_after = df_cleaned.isna().sum()
desc_after = df_cleaned.describe()

print(f"New dataset shape: {shape_after}")
print("\nMissing values after using dropna():")
print(nonan_after)
print("\nDataset description after using dropna():")
print(desc_after)

New dataset shape: (20433, 10)

Missing values after using dropna():
longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

Dataset description after using dropna():
          longitude      latitude  housing_median_age   total_rooms  \
count  20433.000000  20433.000000        20433.000000  20433.000000   
mean    -119.570689     35.633221           28.633094   2636.504233   
std        2.003578      2.136348           12.591805   2185.269567   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1450.000000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.720000           37.000000   3143.000000   
max     -114.310000     41.950000           52.000000  39320.000000

The summaries for the report after cleaning the dataset now differ slightly from the report before cleaning the dataset. The most notable being the count, mean, and standard deviation. This is because we removed the rows with missing values and now for all the columns in the 'after' report now have a count of 20433 which can affect the mean, which can, in turn, affect the standard deviation.

___

## 8.)

In [23]:
new_url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df_titanic = pd.read_csv(new_url)
df_titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

___

## 8.a)

I will explain `df.groupby('col1')['col2'].describe()` in different parts:

First, the `df.groupby('col1')` method groups the DataFrame using the values from 'col1' and returns a grouped or GroupBy object that corresponds to a unique value in 'col1':


In [24]:
# Let's say we want to find out how many survived based on their sex. Let's first group the dataset by 'sex'.
df_titanic.groupby('sex')

In [25]:
# We can observe here that it returns a GroupBy object.

# Next, the ['col2'] in groupby('col1')['col2'].describe() indicates the specified column where subsequent operations will be performed for each group.

# Here we replace 'col2' with the column 'survived'
df_titanic.groupby('sex')['survived']


In [26]:
# It still returns a GroupBy object, but with a different hexadecimal memory address

# To provide information we can actually understand, this is where describe() comes in.
# The method describe(), as demonstrated before, generates the descriptive statistics of the dataset. 
# In the context of groupby('col1')['col2'].describe(), describe() here is performed specifically on the selected column -- which is the column 'survive' -- corresponding to each unique value in 'col1'.

# To reiterate, the groupby() method takes 'col1' as an argument, then we specify which columns (enclosed in brackets -- ['col2']) we want to see be corresponded with a unique value in 'col1'. 
# After that, we use describe() to generate the descriptive statistics of the specified column, which is 'col2'.

# Using them altogether:
df_titanic.groupby('sex')['survived'].describe()

# Here I intended to generate descriptive statistics of the survival rate based on whether or not they are male or female.

count      mean       std  min  25%  50%  75%  max
sex                                                       
female  314.0  0.742038  0.438211  0.0  0.0  1.0  1.0  1.0
male    577.0  0.188908  0.391775  0.0  0.0  0.0  0.0  1.0

___

## 8.b)

In [27]:
# Demonstrating describe()
df_titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [28]:
# Demonstrating df.groupby("col1")["col2"].describe()
df_titanic.groupby('age')['survived'].describe()

count  mean  std  min  25%  50%  75%  max
age                                             
0.42     1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
0.67     1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
0.75     2.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
0.83     2.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
0.92     1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
...      ...   ...  ...  ...  ...  ...  ...  ...
70.00    2.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
70.50    1.0   0.0  NaN  0.0  0.0  0.0  0.0  0.0
71.00    2.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
74.00    1.0   0.0  NaN  0.0  0.0  0.0  0.0  0.0
80.00    1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0

[88 rows x 8 columns]

The fundamental difference between the two is that the *count* in just using `describe()` reflects the number of non-missing values in an entire column across the dataset, while the *count* in using `df.groupby("col1")["col2"].describe()` reflects the non-missing values in 'col2' within each unique group in 'col1'.

It can be observed that `df.groupby("col1")["col2"].describe()` has its *count*s grouped according to each unique value in 'col1'.
___

## 8.c)

ChatGPT gives me a quicker and more informative solution compared to when using a search engine. When using Google, I had to pinpoint the most accurate and relevant solution which can be inefficient when compared to ChatGPT.


# Comparing ChatGPT and Google solutions:

## 8.c.i)

### NameError: name 'pd' is not defined

ChatGPT: The error NameError: name 'pd' is not defined indicates that the pandas library (pd) hasn't been imported into your code. To resolve this, make sure you have imported the pandas library at the beginning of your script. You can do this with the following line:
`import pandas as pd`
Once pandas is imported, the abbreviation pd will be recognized, and you should be able to proceed without the error.

Google: To resolve the NameError: name 'pd' is not defined , you need to import Pandas before using it. 

## 8.c.ii)

### HTTPError: HTTP Error 404: Not Found

ChatGPT: The HTTPError: HTTP Error 404: Not Found error typically occurs when the URL you are trying to access is incorrect or the file you're trying to download doesn't exist at that location. ChatGPT also gave me steps to troubleshoot that can be read in the chat log.

Google gave me mixed solutions, and there were troubleshooting suggestions but I found none that would work in relation to my error.

## 8.c.iii)

### NameError: name 'DF_titanic' is not defined

ChatGPT: (view chat log)

Google: To avoid the NameError , you need to make sure that your DataFrame df is declared before it's accessed.

## 8.c.iv)

### SyntaxError: unmatched ')'

ChatGPT: (view chat log)

The error is pretty obvious so I couldn't find a similar error among my searches. Google didn't provide a simple answer.

## 8.c.v)

### AttributeError: 'SeriesGroupBy' object has no attribute 'describle'

ChatGPT: (view chat log)

Google provided me simple troubleshooting suggestions but I find that ChatGPT is more specific with its generated solution.

## 8.c.vi)

### KeyError: 'Sex' | KeyError: 'aGe'

ChatGPT: (view chat log)

Google provided me with a straightforward answer surprisingly; I did not have to click on any links in the searches.

## 8.c.vii)

### NameError: name 'survived' is not defined

ChatGPT: (view chat log)

Google provided me a straightforward answer.
___


## 9.)

Somewhat

___
# ChatGPT chat log summaries

### Finding a dataset: 
https://chatgpt.com/share/ed8475a3-c16f-47ac-a0b1-4312e90e34c9

I, unfortunately, could not ask for a summary for this chat log because I reached the limit. Basically, the summary would be that I asked for a dataset with missing values and had to further specify that I want a direct link to the csv file that was not annotated. I settled for the California Housing Prices Dataset, and asked how to understand the size (or dimensions) of the dataset.

### Meanings, terminology, and how to properly analyze dataset: 
https://chatgpt.com/share/4be2bc86-98e7-4a70-9d25-8f6b85c59fd1

### Titanic Data Analysis Help: 
https://chatgpt.com/share/683148d2-45e9-4e51-b104-3b95b4a44fa9

### Identifying Pandas Errors: 
https://chatgpt.com/share/c96093f8-609a-4f8c-b779-244e59bbaa4d